import type { Task } from "./session";

// Synthetic sessions for designing the UI in development (`?demo`). Never shown in production builds.
export const demoTasks: Task[] = [
  {
    id: "demo-json-flag",
    title: "Flag --json na CLI",
    workspace: "cd-ai",
    branch: "main",
    status: "completed",
    updated: "agora",
    phase: "review",
    model: "qwen3-coder:30b",
    modelLoaded: true,
    contextUsed: 11_400,
    contextLimit: 32_768,
    events: [
      { kind: "user", text: "Adiciona uma flag `--json` na CLI que imprime o AppInfo em JSON." },
      { kind: "assistant", text: "Vou ler a CLI e o core antes de mexer em qualquer coisa." },
      { kind: "read", path: "apps/cli/src/main.rs" },
      { kind: "read", path: "crates/agent-core/src/lib.rs" },
      { kind: "search", query: "serde_json", matches: 0 },
      { kind: "read", path: "apps/cli/Cargo.toml" },
      {
        kind: "assistant",
        text: "O `AppInfo` já deriva `Serialize`. Falta adicionar `serde_json` na CLI e um ramo novo no `match` de argumentos.",
      },
      { kind: "edit", path: "apps/cli/Cargo.toml", added: 1, removed: 0 },
      { kind: "edit", path: "apps/cli/src/main.rs", added: 9, removed: 1 },
      { kind: "command", command: "cargo clippy -p cd-ai-cli -- -D warnings", exitCode: 0, durationMs: 8400 },
      {
        kind: "command",
        command: "cargo test --workspace",
        exitCode: 101,
        durationMs: 6100,
        output: [
          "running 2 tests",
          "test tests::app_info_uses_crate_version ... ok",
          "test tests::usage_lists_every_flag ... FAILED",
          "",
          "failures:",
          '    assertion failed: USAGE.contains("--json")',
          "",
          "test result: FAILED. 1 passed; 1 failed",
        ].join("\n"),
      },
      {
        kind: "assistant",
        text: "O teste do texto de ajuda não conhecia a flag nova. Atualizei o `USAGE` em vez de afrouxar o teste.",
      },
      { kind: "edit", path: "apps/cli/src/main.rs", added: 1, removed: 1 },
      {
        kind: "command",
        command: "cargo test --workspace",
        exitCode: 0,
        durationMs: 5200,
        output: "test result: ok. 2 passed; 0 failed",
      },
      {
        kind: "command",
        command: "cargo run -q -p cd-ai-cli -- --json",
        exitCode: 0,
        durationMs: 1300,
        output: '{"name":"cd-ai","version":"0.1.0"}',
      },
      {
        kind: "report",
        validated: true,
        summary: "`cd-ai --json` imprime o AppInfo em JSON.",
        checks: [
          { label: "Lint", command: "cargo clippy -p cd-ai-cli -- -D warnings", ok: true },
          { label: "Testes", command: "cargo test --workspace", ok: true },
          { label: "Execução", command: "cargo run -q -p cd-ai-cli -- --json", ok: true },
        ],
      },
    ],
  },
  {
    id: "demo-path-validation",
    title: "Validar paths do workspace",
    workspace: "cd-ai",
    branch: "main",
    status: "running",
    updated: "2 min",
    phase: "validate",
    model: "qwen3-coder:30b",
    modelLoaded: true,
    contextUsed: 27_900,
    contextLimit: 32_768,
    events: [
      {
        kind: "user",
        text: "Cria a validação de paths do workspace: canonicalizar, bloquear `../` e symlinks que saem da pasta.",
      },
      { kind: "read", path: "SPEC.md" },
      { kind: "read", path: "docs/decisions/0001-plataforma.md" },
      { kind: "search", query: "canonicalize", matches: 0 },
      { kind: "read", path: "crates/agent-core/src/workspace.rs", error: "arquivo não encontrado" },
      {
        kind: "assistant",
        text: "Ainda não existe módulo de workspace. Vou criar `workspace.rs` no `agent-core`, com testes para os casos de Windows e Linux.",
      },
      { kind: "edit", path: "crates/agent-core/src/workspace.rs", added: 118, removed: 0 },
      { kind: "edit", path: "crates/agent-core/src/lib.rs", added: 2, removed: 0 },
      { kind: "command", command: "cargo test -p agent-core workspace", exitCode: null, durationMs: 0 },
    ],
  },
  {
    id: "demo-next-build",
    title: "Lentidão no build do Next",
    workspace: "cd-ai",
    branch: "main",
    status: "completed_unvalidated",
    updated: "ontem",
    phase: "review",
    model: "qwen3:4b",
    modelLoaded: false,
    contextUsed: 6_200,
    contextLimit: 8_192,
    events: [
      { kind: "user", text: "O `next build` ficou lento. Descobre por quê." },
      { kind: "read", path: "apps/desktop/next.config.ts" },
      { kind: "read", path: "apps/desktop/package.json" },
      { kind: "search", query: 'from "@/', matches: 7 },
      {
        kind: "assistant",
        text: "Nada no código explica a lentidão. O mais provável é o antivírus escaneando `node_modules` e `.next`, mas não consigo medir isso daqui.",
      },
      {
        kind: "report",
        validated: false,
        summary: "Hipótese sem medição: excluir as pastas de build do antivírus.",
        checks: [{ label: "Build antes e depois", command: "bun run --cwd apps/desktop build", ok: null }],
      },
    ],
  },
];
