import type { Task } from "./session";

// Synthetic sessions for designing the UI in development (`?demo`). Never shown in production builds.
// The task in flight is the one the composer treats as running, so Cancelar and the course
// correction are inspectable too.
export const demoRunningId = "demo-path-validation";

export const demoTasks: Task[] = [
  {
    id: "demo-json-flag",
    title: "Flag --json na CLI",
    workspace: "cd-ai",
    branch: "main",
    status: "completed",
    updated: "agora",
    phase: "review",
    model: "qwen3-coder:30b",
    modelLoaded: true,
    contextUsed: 11_400,
    contextLimit: 32_768,
    events: [
      { kind: "user", text: "Adiciona uma flag `--json` na CLI que imprime o AppInfo em JSON." },
      { kind: "assistant", text: "Vou ler a CLI e o core antes de mexer em qualquer coisa." },
      { kind: "read", path: "apps/cli/src/main.rs" },
      { kind: "read", path: "crates/agent-core/src/lib.rs" },
      { kind: "search", query: "serde_json", matches: 0 },
      { kind: "read", path: "apps/cli/Cargo.toml" },
      {
        kind: "assistant",
        text: "O `AppInfo` já deriva `Serialize`. Falta adicionar `serde_json` na CLI e um ramo novo no `match` de argumentos.",
      },
      { kind: "edit", path: "apps/cli/Cargo.toml", added: 1, removed: 0 },
      { kind: "edit", path: "apps/cli/src/main.rs", added: 9, removed: 1 },
      { kind: "command", command: "cargo clippy -p cd-ai-cli -- -D warnings", exitCode: 0, durationMs: 8400 },
      {
        kind: "command",
        command: "cargo test --workspace",
        exitCode: 101,
        durationMs: 6100,
        output: [
          "running 2 tests",
          "test tests::app_info_uses_crate_version ... ok",
          "test tests::usage_lists_every_flag ... FAILED",
          "",
          "failures:",
          '    assertion failed: USAGE.contains("--json")',
          "",
          "test result: FAILED. 1 passed; 1 failed",
        ].join("\n"),
      },
      {
        kind: "assistant",
        text: "O teste do texto de ajuda não conhecia a flag nova. Atualizei o `USAGE` em vez de afrouxar o teste.",
      },
      { kind: "edit", path: "apps/cli/src/main.rs", added: 1, removed: 1 },
      {
        kind: "command",
        command: "cargo test --workspace",
        exitCode: 0,
        durationMs: 5200,
        output: "test result: ok. 2 passed; 0 failed",
      },
      {
        kind: "command",
        command: "cargo run -q -p cd-ai-cli -- --json",
        exitCode: 0,
        durationMs: 1300,
        output: '{"name":"cd-ai","version":"0.1.0"}',
      },
      {
        kind: "report",
        validated: true,
        summary: "`cd-ai --json` imprime o AppInfo em JSON.",
        checks: [
          { label: "Lint", command: "cargo clippy -p cd-ai-cli -- -D warnings", ok: true },
          { label: "Testes", command: "cargo test --workspace", ok: true },
          { label: "Execução", command: "cargo run -q -p cd-ai-cli -- --json", ok: true },
        ],
      },
    ],
  },
  {
    id: "demo-path-validation",
    title: "Validar paths do workspace",
    workspace: "cd-ai",
    branch: "main",
    status: "running",
    updated: "2 min",
    phase: "validate",
    model: "qwen3-coder:30b",
    modelLoaded: true,
    contextUsed: 27_900,
    contextLimit: 32_768,
    events: [
      {
        kind: "user",
        text: "Cria a validação de paths do workspace: canonicalizar, bloquear `../` e symlinks que saem da pasta.",
      },
      { kind: "read", path: "SPEC.md" },
      { kind: "read", path: "docs/decisions/0001-plataforma.md" },
      { kind: "search", query: "canonicalize", matches: 0 },
      { kind: "read", path: "crates/agent-core/src/workspace.rs", error: "arquivo não encontrado" },
      {
        kind: "assistant",
        text: "Ainda não existe módulo de workspace. Vou criar `workspace.rs` no `agent-core`, com testes para os casos de Windows e Linux.",
      },
      { kind: "edit", path: "crates/agent-core/src/workspace.rs", added: 118, removed: 0 },
      { kind: "edit", path: "crates/agent-core/src/lib.rs", added: 2, removed: 0 },
      { kind: "command", command: "cargo test -p agent-core workspace", exitCode: null, durationMs: 0 },
    ],
  },
  {
    id: "demo-approval-command",
    title: "Resolver os avisos do clippy",
    workspace: "cd-ai",
    branch: "main",
    status: "waiting_approval",
    updated: "agora",
    phase: "implement",
    model: "qwen3-coder:30b",
    modelLoaded: true,
    contextUsed: 9_100,
    contextLimit: 32_768,
    events: [
      { kind: "user", text: "O `cargo clippy` está reclamando no `agent-core`. Resolve os avisos." },
      { kind: "read", path: "crates/agent-core/src/tools/mod.rs" },
      { kind: "search", query: "clippy::", summary: "3 resultados em 2 arquivos" },
      {
        kind: "command",
        id: 1,
        command: "cargo clippy -p agent-core -- -D warnings",
        exitCode: 101,
        durationMs: 9200,
        output: [
          "warning: this expression creates a reference which is immediately dereferenced",
          "   --> crates/agent-core/src/tools/mod.rs:212:31",
          "",
          "error: `agent-core` (lib) generated 3 warnings",
        ].join("\n"),
      },
      {
        kind: "assistant",
        text: "São três avisos mecânicos, e o próprio clippy sabe aplicá-los. Como `--fix` reescreve arquivos, preciso da sua aprovação.",
      },
    ],
    pendingApproval: {
      id: "aprv_0007",
      action: {
        type: "runCommand",
        argv: ["cargo", "clippy", "--fix", "--allow-dirty", "-p", "agent-core"],
        class: "write",
        cwd: "C:/Users/dev/cd-ai",
      },
    },
  },
  {
    id: "demo-approval-edit",
    title: "Corrigir a função de soma",
    workspace: "soma",
    branch: "main",
    status: "waiting_approval",
    updated: "agora",
    phase: "implement",
    model: "qwen3-coder:30b",
    modelLoaded: true,
    contextUsed: 4_300,
    contextLimit: 32_768,
    events: [
      { kind: "user", text: "O teste de soma falha. Corrige e roda os testes." },
      { kind: "read", path: "src/soma.test.ts" },
      { kind: "read", path: "src/soma.ts" },
      { kind: "failure", tool: "read_file", message: "arquivo não encontrado: src/soma.js" },
      {
        kind: "assistant",
        text: "A função subtrai em vez de somar. A correção é de uma linha.",
      },
    ],
    pendingApproval: {
      id: "aprv_0008",
      action: {
        type: "editFile",
        path: "src/soma.ts",
        diff: [
          "--- before",
          "+++ after",
          "-export function soma(a: number, b: number) {",
          "-  return a - b;",
          "+export function soma(a: number, b: number): number {",
          "+  return a + b;",
          " }",
          "",
        ].join("\n"),
      },
    },
  },
  {
    id: "demo-next-build",
    title: "Lentidão no build do Next",
    workspace: "cd-ai",
    branch: "main",
    status: "completed_unvalidated",
    updated: "ontem",
    phase: "review",
    model: "qwen3:4b",
    modelLoaded: false,
    contextUsed: 6_200,
    contextLimit: 8_192,
    events: [
      { kind: "user", text: "O `next build` ficou lento. Descobre por quê." },
      { kind: "read", path: "apps/desktop/next.config.ts" },
      { kind: "read", path: "apps/desktop/package.json" },
      { kind: "search", query: 'from "@/', matches: 7 },
      {
        kind: "assistant",
        text: "Nada no código explica a lentidão. O mais provável é o antivírus escaneando `node_modules` e `.next`, mas não consigo medir isso daqui.",
      },
      {
        kind: "report",
        validated: false,
        summary: "Hipótese sem medição: excluir as pastas de build do antivírus.",
        checks: [{ label: "Build", command: "bun run --cwd apps/desktop build", ok: null }],
      },
    ],
    // A normal ending says nothing the report has not said, so there is no "a tarefa parou" line.
    stopCause: { kind: "finished" },
  },
  {
    id: "demo-interrupted",
    title: "Migrar o store para SQLite",
    workspace: "cd-ai",
    branch: "main",
    status: "cancelled",
    updated: "3 h",
    phase: "implement",
    model: "qwen3-coder:30b",
    modelLoaded: true,
    contextUsed: 18_600,
    contextLimit: 32_768,
    events: [
      { kind: "user", text: "Troca o store de arquivos por SQLite, mantendo o mesmo formato de evento." },
      { kind: "read", path: "crates/agent-core/src/agent/storage.rs" },
      { kind: "read", path: "crates/agent-core/Cargo.toml" },
      { kind: "search", query: "load_events", summary: "6 resultados em 3 arquivos" },
      {
        kind: "assistant",
        text: "O `storage.rs` grava três arquivos por tarefa. Vou começar pelo schema e só depois mexer na escrita.",
      },
      { kind: "edit", path: "crates/agent-core/src/agent/storage.rs", added: 42, removed: 7 },
    ],
    // The app closed with work in flight (D9): the only stop nobody decided, and the only one the
    // conversation offers to pick up again.
    stopCause: { kind: "interrupted" },
    stopReason: "o app fechou com ela em andamento",
  },
];
