// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Which prompt and tool set the model is running under. Default `Coder` so states written
 * before Fase 10 resume with write tools.
 */
export type AgentRole = "explorer" | "coder";
