// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentRole } from "./AgentRole";
import type { CheckpointKind } from "./CheckpointKind";
import type { ModelCategory } from "./ModelCategory";
import type { RollbackSkip } from "./RollbackSkip";
import type { StopReason } from "./StopReason";
import type { TaskReport } from "./TaskReport";
import type { TaskStatus } from "./TaskStatus";
import type { TaskSummary } from "./TaskSummary";
import type { ToolEvent } from "./ToolEvent";

/**
 * Everything the loop tells the outside world. Free text here is already redacted.
 *
 * Read back as well as written: `TaskStore::load_events` replays a task as
 * `AgentEventMessage`, not as raw JSON (plan 015, Part D, step 0).
 */
export type AgentEvent = { "event": "taskStarted", "data": { summary: TaskSummary, } } | { "event": "statusChanged", "data": { status: TaskStatus, reason: string | null, } } | { "event": "userMessage", "data": { text: string, } } | { "event": "modelTurnStarted", "data": { iteration: number, model: string, } } | { "event": "token", "data": { content: string, } } | { "event": "thinking", "data": { content: string, } } | { "event": "modelTurnCompleted", "data": { promptTokens: number, genTokens: number, promptMs: number, genMs: number, } } | { "event": "assistantMessage", "data": { content: string, } } | { "event": "toolCallRequested", "data": { tool: string, input: Record<string, unknown>, } } | { "event": "toolCallFinished", "data": { tool: string, ok: boolean, detail: string, output: string | null, } } | { "event": "tool", "data": ToolEvent } | { "event": "contextTrimmed", "data": { removedMessages: number, estimatedTokens: number, } } | { "event": "contextBudgetCut", "data": { section: string, tokensBefore: number, tokensAfter: number, } } | { "event": "contextCompacted", "data": { estimatedTokens: number, reason: string, } } | { "event": "roleChanged", "data": { role: AgentRole, reason: string, } } | { "event": "skillsDetected", "data": { names: Array<string>, } } | { "event": "skillLoaded", "data": { name: string, reason: string, } } | { "event": "skillSkipped", "data": { name: string, reason: string, } } | { "event": "modelRouted", "data": { category: ModelCategory, model: string, numCtx: number, reason: string, } } | { "event": "memoryLoaded", "data": { ids: Array<string>, } } | { "event": "retrying", "data": { attempt: number, reason: string, } } | { "event": "taskFinished", "data": { status: TaskStatus, stopReason: StopReason, report: TaskReport, } } | { "event": "checkpointCreated", "data": { commit: string, kind: CheckpointKind, } } | { "event": "rollbackCompleted", "data": { restored: Array<string>, skipped: Array<RollbackSkip>, } };
