// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { StopReason } from "./StopReason";
import type { TaskReport } from "./TaskReport";
import type { TaskStatus } from "./TaskStatus";
import type { TaskSummary } from "./TaskSummary";
import type { ToolEvent } from "./ToolEvent";

/**
 * What actually travels over the channel: task identity, order and an instant on every event,
 * flattened so a consumer reads `{ event, data, taskId, sequence, at }` (D12).
 */
export type AgentEventMessage = { taskId: string, sequence: number, at: string, } & ({ "event": "taskStarted", "data": { summary: TaskSummary, } } | { "event": "statusChanged", "data": { status: TaskStatus, reason: string | null, } } | { "event": "userMessage", "data": { text: string, } } | { "event": "modelTurnStarted", "data": { iteration: number, model: string, } } | { "event": "token", "data": { content: string, } } | { "event": "thinking", "data": { content: string, } } | { "event": "modelTurnCompleted", "data": { promptTokens: number, genTokens: number, promptMs: number, genMs: number, } } | { "event": "assistantMessage", "data": { content: string, } } | { "event": "toolCallRequested", "data": { tool: string, input: Record<string, unknown>, } } | { "event": "toolCallFinished", "data": { tool: string, ok: boolean, detail: string, output: string | null, } } | { "event": "tool", "data": ToolEvent } | { "event": "contextTrimmed", "data": { removedMessages: number, estimatedTokens: number, } } | { "event": "retrying", "data": { attempt: number, reason: string, } } | { "event": "taskFinished", "data": { status: TaskStatus, stopReason: StopReason, report: TaskReport, } });
