// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Operational limits of the loop (plan 015, D7; SPEC §11.1). Not a token budget:
 * inference is local and has no cost (decision 0008).
 */
export type AgentLimits = { maxIterations: number, maxModelRetries: number, 
/**
 * Consecutive invalid tool calls tolerated before the task fails.
 */
maxInvalidToolCalls: number, modelTurnTimeoutMs: number, taskTimeoutMs: number, };
