// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CommandClass } from "./CommandClass";

/**
 * The exact thing the user is asked to approve (design §5.3). Never a model summary.
 */
export type ApprovalAction = { "type": "runCommand", argv: Array<string>, class: CommandClass, cwd: string, } | { "type": "editFile", path: string, diff: string, } | { "type": "writeFile", path: string, size: number, } | { "type": "readFile", path: string, };
