// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ApprovalAction } from "./ApprovalAction";

/**
 * A single open approval, with an idempotent id (`aprv_NNNN`, design §5.3).
 */
export type ApprovalRequest = { id: string, taskId: string, at: string, action: ApprovalAction, };
