// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ModelToolCall } from "./ModelToolCall";

export type ChatMessage = { role: string, content: string, 
/**
 * Native tool calls the model asked for, mirroring Ollama's `message.tool_calls`.
 */
tool_calls?: Array<ModelToolCall>, 
/**
 * Only on `role: "tool"` messages, carrying a tool result back to the model.
 */
tool_name?: string | null, };
