// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChatMessage } from "./ChatMessage";

export type ChatRequest = { model: string, messages: Array<ChatMessage>, 
/**
 * Always explicit: the runtime default can silently truncate the prompt (SPEC §4).
 */
numCtx: number, };
