// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ChatEvent = { "event": "token", "data": { content: string, } } | { "event": "thinking", "data": { content: string, } } | { "event": "done", "data": { promptTokens: number, genTokens: number, promptMs: number, genMs: number, } } | { "event": "error", "data": { message: string, } };
