// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CheckpointKind } from "./CheckpointKind";

/**
 * One commit in the shadow repo, hanging off the task that produced it.
 */
export type Checkpoint = { commit: string, kind: CheckpointKind, createdAt: string, };
