// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Why a shadow-repo commit was taken (plan 019, SPEC §21).
 */
export type CheckpointKind = "baseline" | "afterWrite" | "beforeDestructive";
