// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One command the task ran. Evidence for the report (SPEC §2).
 */
export type CommandRecord = { argv: Array<string>, 
/**
 * `None` when the command timed out or was cancelled (plan 015, maintenance notes).
 */
exitCode: number | null, durationMs: number, };
