// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CommandResult = { id: number, exitCode: number | null, durationMs: number, output: string, truncated: boolean, timedOut: boolean, };
