// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Deterministic classification of a command line (design §4), pure function.
 */
export type CommandClass = "read" | "validate" | "write" | "network" | "destructive" | "unknown";
