// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type EditFileResult = { path: string, changedLines: number, removed: number, added: number, hashBefore: string, hashAfter: string, fuzzy: boolean, };
