// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One file the task changed, with the hash that proves the content afterwards.
 */
export type FileChange = { path: string, hashAfter: string, 
/**
 * The file was there before the task's first write to it. When the baseline has no copy (a
 * gitignored file), rollback cannot restore it and must not delete it either.
 */
existedBefore: boolean, };
