// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What kind of fact this is (SPEC §24.2).
 */
export type MemoryKind = "rule" | "architecture" | "preference" | "constraint" | "learned";
