// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MemoryKind } from "./MemoryKind";

/**
 * One memory entry. `stale` is how the user invalidates without deleting.
 */
export type MemoryEntry = { id: string, kind: MemoryKind, text: string, createdAt: string, updatedAt: string, stale: boolean, };
