// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ModelFunctionCall = { name: string, 
/**
 * Ollama sends the arguments already parsed as a JSON object.
 */
arguments: Record<string, unknown>, };
