// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ModelFunctionCall } from "./ModelFunctionCall";

/**
 * One entry of Ollama's `message.tool_calls`.
 */
export type ModelToolCall = { function: ModelFunctionCall, };
