// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LoadedModel } from "./LoadedModel";
import type { ModelInfo } from "./ModelInfo";

export type OllamaStatus = { reachable: boolean, version: string | null, models: Array<ModelInfo>, loaded: Array<LoadedModel>, error: string | null, };
