// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How a permission decision came about (design §5.3: `denied`/`auto`/`granted`).
 *
 * `Deserialize` too, so a stored `ToolEvent` can be read back for a typed replay
 * (plan 015, Part D, step 0).
 */
export type PermissionDecision = "denied" | "auto" | "granted";
