// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How a permission decision came about (design §5.3: `denied`/`auto`/`granted`).
 */
export type PermissionDecision = "denied" | "auto" | "granted";
