// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * User-facing permission mode (SPEC §20.4). Default is Ask: the v1 behaviour before a sandbox.
 */
export type PermissionMode = "ask" | "auto" | "fullAccess";
