// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SecretFileView } from "./SecretFileView";

export type ReadFileResult = { path: string, text: string, startLine: number, endLine: number, totalLines: number, isTruncated: boolean, redacted: number, secret: SecretFileView | null, };
