// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One file the safe rollback refused to touch, with the diff the user needs to decide.
 */
export type RollbackSkip = { path: string, reason: string, diff: string, };
