// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RollbackSkip } from "./RollbackSkip";

/**
 * What a rollback did. Paths not listed here were never candidates (the agent did not write them).
 */
export type RollbackResult = { restored: Array<string>, skipped: Array<RollbackSkip>, alreadyClean: Array<string>, };
