// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What the UI and the policy need to know. `available` is filesystem AND network block.
 */
export type SandboxStatus = { available: boolean, filesystem: boolean, networkBlock: boolean, platform: string, 
/**
 * Short reason in pt-BR: shown when FULL ACCESS is off.
 */
detail: string, };
