// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EnvKey } from "./EnvKey";

/**
 * Friendly view of an approved secret file: keys only for `.env`, metadata for keys (design §6.4).
 */
export type SecretFileView = { "kind": "dotEnv", keys: Array<EnvKey>, } | { "kind": "privateKey", 
/**
 * e.g. "RSA", "OPENSSH".
 */
keyKind: string, 
/**
 * short hex digest of the PEM body, for identification without the key material.
 */
fingerprint: string, } | { "kind": "credentials", 
/**
 * Nothing to show: only the fact that the file matched a credentials pattern.
 */
matchedPattern: string, };
