// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What kind of secret a path or content looks like (design §6.1).
 */
export type SecretKind = ".env" | "chavePrivada" | "credentials";
