// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A skill the orchestrator loaded for a task, with the reason the router kept it (SPEC §23).
 */
export type SelectedSkill = { name: string, reason: string, };
