// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PermissionMode } from "./PermissionMode";

export type Settings = { 
/**
 * Model the user last picked in the UI; `None` until they pick one.
 */
model: string | null, 
/**
 * ASK / AUTO / FULL ACCESS (SPEC §20.4). Default ASK.
 */
permissionMode: PermissionMode, 
/**
 * Optional FAST / CODER / REASONER names (plan 022). Empty = use `model`.
 */
fast: string | null, coder: string | null, reasoner: string | null, 
/**
 * Opt-in local trajectories (SPEC §25). Off by default.
 */
trajectories: boolean, };
