// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Settings = { 
/**
 * Model the user last picked in the UI; `None` until they pick one.
 */
model: string | null, };
