// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A skill the router considered and then dropped, with why (SPEC §17.3).
 */
export type SkillSkip = { name: string, reason: string, };
