// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Why the loop stopped. Every terminal status carries one (SPEC §11.1).
 */
export type StopReason = { "kind": "finished" } | { "kind": "verified" } | { "kind": "maxIterations" } | { "kind": "taskTimeout" } | { "kind": "loopDetected", detail: string, } | { "kind": "invalidToolCalls" } | { "kind": "modelError", message: string, } | { "kind": "contextExhausted" } | { "kind": "cancelled" } | { "kind": "interrupted" };
