// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CommandRecord } from "./CommandRecord";

/**
 * What the task delivered. `validated` is always false in phase 5 (D11): the Verifier is phase 8.
 */
export type TaskReport = { 
/**
 * Final model text, redacted.
 */
summary: string, validated: boolean, evidence: Array<CommandRecord>, filesChanged: Array<string>, };
