// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TaskMetrics } from "./TaskMetrics";
import type { TaskSummary } from "./TaskSummary";

/**
 * A task as listed in the workspace history (plan 019, SPEC §24.1).
 */
export type TaskHistoryEntry = { summary: TaskSummary, filesChanged: Array<string>, commandCount: number, checkpoint: string | null, rolledBack: boolean, createdAt: string, metrics: TaskMetrics, };
