// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Counters worth showing in the UI; never a billing figure (decision 0008).
 */
export type TaskMetrics = { promptTokens: number, genTokens: number, modelMs: number, 
/**
 * Time the tools actually ran. Waiting for a human to approve is not tool work, so it is
 * counted apart in `approval_wait_ms`.
 */
toolMs: number, 
/**
 * Time the task sat blocked on an approval prompt. Absent from states written before this
 * field existed, hence the default.
 */
approvalWaitMs: number, 
/**
 * Last `chars/4` estimate of the conversation sent to the model (plan 020).
 */
estimatedTokens: number, 
/**
 * Peak of that estimate across turns.
 */
peakEstimatedTokens: number, };
