// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CommandRecord } from "./CommandRecord";
import type { FileChange } from "./FileChange";
import type { StopReason } from "./StopReason";
import type { TaskMetrics } from "./TaskMetrics";
import type { TaskStatus } from "./TaskStatus";

/**
 * Everything about a task that survives a restart. Written to `tasks/<id>/state.json`.
 */
export type TaskState = { id: string, 
/**
 * Workspace root, for display and for filtering the task list.
 */
workspace: string, request: string, model: string, numCtx: number, status: TaskStatus, stopReason: StopReason | null, createdAt: string, updatedAt: string, iterations: number, filesRead: Array<string>, filesChanged: Array<FileChange>, commands: Array<CommandRecord>, 
/**
 * Redacted before reaching disk (D8).
 */
errors: Array<string>, retries: number, metrics: TaskMetrics, };
