// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How the orchestrator labelled this task (SPEC §11.2).
 */
export type TaskKind = "question" | "trivial" | "normal" | "complex";
