// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentRole } from "./AgentRole";
import type { Checkpoint } from "./Checkpoint";
import type { CommandRecord } from "./CommandRecord";
import type { FileChange } from "./FileChange";
import type { ModelCategory } from "./ModelCategory";
import type { SelectedSkill } from "./SelectedSkill";
import type { StopReason } from "./StopReason";
import type { TaskKind } from "./TaskKind";
import type { TaskMetrics } from "./TaskMetrics";
import type { TaskStatus } from "./TaskStatus";

/**
 * Everything about a task that survives a restart. Written to `tasks/<id>/state.json`.
 */
export type TaskState = { id: string, 
/**
 * Workspace root, for display and for filtering the task list.
 */
workspace: string, request: string, 
/**
 * Task this one continues, when the request came right after another one in the same
 * workspace. Only the previous report is inherited, never its transcript: a task still has
 * one request, and continuity is a chain of tasks, not a task with many turns.
 * Absent from states written before chaining existed, hence the default.
 */
continues: string | null, model: string, numCtx: number, status: TaskStatus, stopReason: StopReason | null, createdAt: string, updatedAt: string, iterations: number, filesRead: Array<string>, filesChanged: Array<FileChange>, commands: Array<CommandRecord>, 
/**
 * Shadow-repo commits of this task (plan 019). Absent from states written before Fase 9.
 */
checkpoints: Array<Checkpoint>, 
/**
 * Set when the user rolled this task back (plan 019). Absent from older states.
 */
rolledBack: boolean, 
/**
 * Role the model is running as (plan 020). Absent from older states → Coder.
 */
role: AgentRole, 
/**
 * Orchestrator label (plan 020). Absent from older states → Normal.
 */
taskKind: TaskKind, 
/**
 * Skills the router loaded (plan 021). Absent from older states → none.
 */
selectedSkills: Array<SelectedSkill>, 
/**
 * Category the Model Router picked (plan 022). Absent from older states → Coder.
 */
modelCategory: ModelCategory, 
/**
 * Human-readable routing reason (SPEC §28). Absent from older states → empty.
 */
routeReason: string, 
/**
 * Quality failures of the Coder in this task (plan 022 D6).
 */
coderFailures: number, 
/**
 * Redacted before reaching disk (D8).
 */
errors: Array<string>, retries: number, metrics: TaskMetrics, };
