// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Status of a task (SPEC §23). There is no `completed` in phase 5: without the Verifier every
 * task that finishes is `completed_unvalidated` (plan 015, D11).
 */
export type TaskStatus = "running" | "waiting_approval" | "completed_unvalidated" | "failed" | "cancelled";
