// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TaskStatus } from "./TaskStatus";

/**
 * A task as listed in the sidebar and by the CLI.
 */
export type TaskSummary = { id: string, title: string, status: TaskStatus, updatedAt: string, model: string, 
/**
 * Id of the task this one continues, so a list can show a chain instead of loose fragments.
 */
continues: string | null, };
