// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Checkpoint } from "./Checkpoint";
import type { CommandRecord } from "./CommandRecord";
import type { FileChange } from "./FileChange";
import type { StopReason } from "./StopReason";
import type { TaskMetrics } from "./TaskMetrics";
import type { TaskStatus } from "./TaskStatus";

/**
 * Everything about a task that survives a restart. Written to `tasks/<id>/state.json`.
 */
export type TaskState = { id: string, 
/**
 * Workspace root, for display and for filtering the task list.
 */
workspace: string, request: string, 
/**
 * Task this one continues, when the request came right after another one in the same
 * workspace. Only the previous report is inherited, never its transcript: a task still has
 * one request, and continuity is a chain of tasks, not a task with many turns.
 * Absent from states written before chaining existed, hence the default.
 */
continues: string | null, model: string, numCtx: number, status: TaskStatus, stopReason: StopReason | null, createdAt: string, updatedAt: string, iterations: number, filesRead: Array<string>, filesChanged: Array<FileChange>, commands: Array<CommandRecord>, 
/**
 * Shadow-repo commits of this task (plan 019). Absent from states written before Fase 9.
 */
checkpoints: Array<Checkpoint>, 
/**
 * Set when the user rolled this task back (plan 019). Absent from older states.
 */
rolledBack: boolean, 
/**
 * Redacted before reaching disk (D8).
 */
errors: Array<string>, retries: number, metrics: TaskMetrics, };
