// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Counters worth showing in the UI; never a billing figure (decision 0008).
 */
export type TaskMetrics = { promptTokens: number, genTokens: number, modelMs: number, 
/**
 * Time the tools actually ran. Waiting for a human to approve is not tool work, so it is
 * counted apart in `approval_wait_ms`.
 */
toolMs: number, 
/**
 * Time the task sat blocked on an approval prompt. Absent from states written before this
 * field existed, hence the default.
 */
approvalWaitMs: number, 
/**
 * Sum of `chars/4` estimates at each model turn (plan 020). The provider's own
 * `prompt_tokens` stays in `prompt_tokens`; ScriptedModel leaves that at 0.
 */
estimatedPromptTokens: number, 
/**
 * Wall time spent assembling context (map, profile, skills, prompt). Plan 023.
 */
contextMs: number, 
/**
 * Repo-map cache hits (disk or in-memory reuse). Plan 023.
 */
cacheHits: number, 
/**
 * Repo-map rebuilds that parsed at least one file. Plan 023.
 */
cacheMisses: number, };
