// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Status of a task (SPEC §23). `completed` is only emitted when the Verifier has evidence
 * (plan 018); a finish without that evidence is `completed_unvalidated`.
 */
export type TaskStatus = "running" | "waiting_approval" | "completed" | "completed_unvalidated" | "failed" | "cancelled";
