// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ToolFunctionSpec } from "./ToolFunctionSpec";

/**
 * One tool offered to the model, in Ollama's function-calling shape.
 */
export type ToolSpec = { type: string, function: ToolFunctionSpec, };
