// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ToolFunctionSpec = { name: string, description: string, 
/**
 * JSON Schema of the parameters.
 */
parameters: Record<string, unknown>, };
