// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ToolError } from "./ToolError";
import type { ToolOutput } from "./ToolOutput";
import type { Truncation } from "./Truncation";

/**
 * The uniform envelope for every tool run (design §2 `ToolResult`). Output-only:
 * nothing here is ever parsed back into the engine, so no `Deserialize`.
 */
export type ToolOutcome = { ok: boolean, data: ToolOutput | null, error: ToolError | null, truncated: Truncation | null, };
