// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ApprovalAction } from "./ApprovalAction";
import type { CommandClass } from "./CommandClass";
import type { PermissionDecision } from "./PermissionDecision";

/**
 * What actually travels over the channel: every event carries task identity and an instant
 * (design §7 — "todo evento carrega task_id e timestamp").
 */
export type ToolEventMessage = { taskId: string, sequence: number, at: string, } & ({ "event": "toolStarted", "data": { tool: string, requestId: number, } } | { "event": "toolCompleted", "data": { tool: string, requestId: number, durationMs: number, truncated: boolean, decision: PermissionDecision, } } | { "event": "toolFailed", "data": { tool: string, requestId: number, message: string, } } | { "event": "fileRead", "data": { path: string, startLine: number, lineCount: number, totalLines: number, truncated: boolean, redacted: number, } } | { "event": "fileChanged", "data": { path: string, diff: string, fuzzy: boolean, hashBefore: string, hashAfter: string, } } | { "event": "commandStarted", "data": { id: number, argv: Array<string>, class: CommandClass, } } | { "event": "commandCompleted", "data": { id: number, exitCode: number | null, durationMs: number, truncated: boolean, outputLen: number, } } | { "event": "approvalRequired", "data": { id: string, taskId: string, action: ApprovalAction, } } | { "event": "approvalGranted", "data": { id: string, } } | { "event": "approvalDenied", "data": { id: string, reason: string | null, } } | { "event": "checkpointCreated", "data": { hash: string, } });
