// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ToolError = { "kind": "outsideWorkspace" } | { "kind": "notFound" } | { "kind": "notAFile" } | { "kind": "notADirectory" } | { "kind": "alreadyExists" } | { "kind": "parseFailed", detail: string, line: number, } | { "kind": "ambiguousEdit" } | { "kind": "editNotFound" } | { "kind": "compoundCommand" } | { "kind": "unknownCommand" } | { "kind": "permissionDenied", reason: string, } | { "kind": "secretDenied" } | { "kind": "cancelled" } | { "kind": "io" } & string;
