// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CommandResult } from "./CommandResult";
import type { EditFileResult } from "./EditFileResult";
import type { ListDirectoryResult } from "./ListDirectoryResult";
import type { ReadFileResult } from "./ReadFileResult";
import type { SearchResult } from "./SearchResult";
import type { WriteFileResult } from "./WriteFileResult";

/**
 * Everything a tool produced, tagged by tool (design §2).
 */
export type ToolOutput = { "tool": "readFile" } & ReadFileResult | { "tool": "search" } & SearchResult | { "tool": "editFile" } & EditFileResult | { "tool": "writeFile" } & WriteFileResult | { "tool": "listDirectory" } & ListDirectoryResult | { "tool": "runCommand" } & CommandResult;
