// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EditFileArgs } from "./EditFileArgs";
import type { ListDirectoryArgs } from "./ListDirectoryArgs";
import type { ReadFileArgs } from "./ReadFileArgs";
import type { RunCommandArgs } from "./RunCommandArgs";
import type { SearchArgs } from "./SearchArgs";
import type { WriteFileArgs } from "./WriteFileArgs";

/**
 * How the model asks for a tool run (design §2). Paths are always workspace-relative or absolute
 * and go through `Workspace::resolve` — no raw path is ever used directly.
 */
export type ToolRequest = { "tool": "readFile" } & ReadFileArgs | { "tool": "search" } & SearchArgs | { "tool": "editFile" } & EditFileArgs | { "tool": "writeFile" } & WriteFileArgs | { "tool": "listDirectory" } & ListDirectoryArgs | { "tool": "runCommand" } & RunCommandArgs;
