// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Why a result was cut short, with instructions the model can follow (design §2).
 */
export type Truncation = { shown: number, total: number, howToGetMore: string, };
