// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What the UI needs to show an open workspace.
 */
export type WorkspaceInfo = { name: string, root: string, };
