// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { IfExists } from "./IfExists";

export type WriteFileArgs = { path: string, content: string, ifExists: IfExists, };
